```yaml
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'stripe-fetch-charges'
      - '--gen2'
      - '--runtime=python311' # <--- CHANGE THIS
      - '--region=australia-southeast1'
      - '--entry-point=fetch_stripe_charges'
      - '--memory=512Mi'
      - '--trigger-http'
