```yaml
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'stripe-fetch-charges'
      - '--runtime=python310'
      - '--region=australia-southeast1'
      - '--entry-point=fetch_stripe_charges'
      - '--memory=512Mi'
      - '--trigger-http'
      - '--set-env-vars=GCP_PROJECT_ID=project-babb1b90-331a-4e2e-a1b'
```
